# Generated by Django 2.2.7 on 2020-06-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200605_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(),
        ),
    ]
